project_id = "qwezfxdfaistnabwqols"

[functions.stock-data]
verify_jwt = false

[functions.sync-stock-data]
verify_jwt = false

[functions.analyze-news-sentiment]
verify_jwt = false

[functions.social-sentiment]
verify_jwt = false

[functions.compute-screener]
verify_jwt = false

[functions.asymmetric-value-screener]
verify_jwt = false


[functions.sync-politician-trades]
verify_jwt = false

[functions.sync-featured-trades]
verify_jwt = false

[functions.simulate-ledger]
verify_jwt = false
